CREATE TABLE IF NOT EXISTS "recruiter_settings" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL UNIQUE,
	"screening_questions_count" integer DEFAULT 6,
	"tech_questions_count" integer DEFAULT 8,
	"hr_questions_count" integer DEFAULT 5,
	"silence_timeout_seconds" integer DEFAULT 3,
	"auto_end_interview" boolean DEFAULT true,
	"ai_voice_id" text DEFAULT 'en-US-falcon',
	"ai_interviewer_name" text DEFAULT 'Alex',
	"interview_tone" text DEFAULT 'professional',
	"screening_prompt" text,
	"tech_prompt" text,
	"hr_prompt" text,
	"closing_message" text,
	"evaluation_strictness" text DEFAULT 'balanced',
	"company_name" text,
	"recruiter_display_name" text,
	"custom_email_subject" text,
	"custom_email_intro" text,
	"reply_to_email" text,
	"invite_expiry_days" integer DEFAULT 7,
	"company_logo_url" text,
	"notify_on_complete" boolean DEFAULT true,
	"notification_email" text,
	"low_score_alert" boolean DEFAULT false,
	"low_score_threshold" integer DEFAULT 5,
	"industry" text,
	"default_location" text,
	"default_currency" text DEFAULT 'USD',
	"timezone" text DEFAULT 'UTC',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
